language: csharp
before_script:
  - nuget restore Src/Userbase.sln
script:
  - xbuild /p:Configuration=Release Src/Userbase.sln
  - mono Src/packages/xunit.runner.console*/tools/xunit.console.exe Src/Com.Ericmas001.Userbase.Test/bin/Release/Com.Ericmas001.Userbase.Test.dll
